version: "3.9"
services:
  jupyterlab:
    container_name: "python3-jupyterlab"
    build:
      context: ./py3
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    command: jupyter lab --ip=0.0.0.0 --port=8888 --allow-root --no-browser --NotebookApp.token=''
    tty: true
    volumes:
      - "./workspace:/home/workspace/"
      - "./py3/root_jupyter:/root/.jupyter"
