# .zshrc

# environment variable
export LANG='ja_JP.UTF-8'
export CLICOLOR=1

# prompt
PS1='%n@%m%f:%F{190}%c%f %{${reset_color}%}%# '
PROMPT='%(?.%F{046}${PS1}.%F{196}${PS1})'

# alias
alias la='ls -a'
alias ll='ls -l'

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# git alias
alias gc='git clone'

# dokcer alias
alias up='docker-compose up -d'
alias down='docker-compose down'
alias build='docker-compose up -d --build'

# functionss
function ol {
  open http:localhost:$1
}

# hook functions
chpwd() {
  if [[ $(pwd) != $HOME ]]; then
  	ls
  fi
}

# source files
if [ -f /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc ]; then
	source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc'
fi

if [ -f /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc ]; then
	source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc'
fi
