# .zshrc

# environment variable

export LANG="ja_JP.UTF-8"
export CLICOLOR=1

# prompt

PROMPT="%(?.%F{046}%n@%m%f:%F{190}%c%f %{${reset_color}%}%# .%F{196}%n@%m%f:%F{190}%c%f %{${reset_color}%}%# )"

# alias

alias la='ls -a'
alias ll='ls -l'

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

alias dc='docker-compose'

# functionss
function ol {
  port=$1
  open http:localhost:${port}
}

# hook functions

chpwd() {
  if [[ $(pwd) != $HOME ]]; then
  	ls
  fi
}
